---
title: "Web-scraping"
author: "Maciej Beręsewicz"
format: 
  html:
    code-fold: true
    self-contained: true
    code-summary: "Show the code"
execute:
  message: false
  warning: false
---

# Pakiety

```{r}
library(rvest)
library(stringi)
```

## Archiwum pracuj.pl

```{r}
read_html("https://archiwum.pracuj.pl/archive/offers?Year=2025&Month=1&PageNumber=1") %>%
  html_nodes("div.offers_item") %>%
  html_nodes("span.offers_item_link_cnt_part") %>%
  html_text() 
```

```{r}
read_html("https://archiwum.pracuj.pl/archive/offers?Year=2025&Month=1&PageNumber=1") %>%
  html_nodes("div.offers_item") %>%
  html_nodes("span.offers_item_desc_date") %>%
  html_text()
```

```{r}
read_html("https://archiwum.pracuj.pl/archive/offers?Year=2025&Month=1&PageNumber=1") %>%
  html_nodes("div.offers_item") %>%
  html_nodes("a.offers_item_link") %>%
  html_attr("href")
```

Rozgrzewka

```{r}

doc <- read_html("https://nabory.kprm.gov.pl/?Ad%5BisAdvancedMode%5D=&Ad%5Bsort%5D=1&Ad%5BpagesCnt%5D=20&Ad%5Bid_province%5D=&Ad%5Bid_city%5D=&Ad%5Bid_institution%5D=&Ad%5Bphrase%5D=&Ad%5Beducation%5D=&Ad%5Bid_institution_position%5D=&Ad%5Bbranch_ids%5D=&Salary%5Bsalary_income_kind%5D=&Salary%5Bsalary_min%5D=&Ad%5Bexperience%5D=&Ad%5Bexperience_period%5D%5B0%5D=0&Ad%5Bexperience_period%5D%5B1%5D=0&Ad%5Bdate_publication%5D=&Ad%5Bdate_expiration%5D=&Ad%5Bprocess_state%5D=1&Recruitment%5Bremote_recruitment%5D=0&Ad%5Bis_disability%5D=0&Ad%5Bis_first_foreigner%5D=0&Ad%5Bis_replacement%5D=0")

```

```{r}

# Numer
doc |>
  html_nodes("div.row") |>
  html_nodes("span.id") |>
  html_text()

```

```{r}

# Data ważności
doc |>
  html_nodes("div.r:nth-child(5)") |>
  html_text() |>
  trimws()

```

```{r}

# Urząd
doc |>
  html_nodes("div.r:nth-child(2)") |>
  html_text() |>
  trimws()

```

```{r}

# Link
doc |>
  html_nodes("div.row") |>
  html_nodes("a") |>
  html_attr("href")

```

Koniec rozgrzewki

##XML

```{r}

library(xml2)
library(jsonlite)

```

Wczytywanie danych z XML
```{r}

doc_xml <- read_xml("https://nabory.kprm.gov.pl/pls/serwis/app.xml")

```

```{r}

doc_xml |>
  html_elements("oferta") |>
  html_element("nazwa_firmy")

```

Wczytywanie danych z json
```{r}

pracuj_link <- "https://www.pracuj.pl/praca/opiekunka-osoby-starszej-w-irlandii-irlandia,oferta,11023969"

doc_json <- read_html(pracuj_link) |>
  html_nodes("script[type='application/ld+json']")

```

```{r}

doc_json |>
  html_text() |>
  fromJSON() -> pracuj_wynik

```

```{r}

str(pracuj_wynik, 1)

```

DOS olx.pl
```{r}

olx_link <- "https://www.olx.pl/api/v1/offers/?user_id=76871193&offset=0&limit=50"

olx_json <- read_json(olx_link)

```

```{r}

str(olx_json$data[[1]], 1)

```


##
```{r}

link_metal <- "https://www.metal-archives.com/bands/Icewall/3540519217"

doc_metal <- read_html_live(link_metal)

```



## Żabka

```{r}
url <- "https://www.zabka.pl/strefa-piwa/"
doc <- read_html(url)
doc
```

```{r}
doc |>
  html_nodes("section.beer-list") |>
  html_nodes("div.beer-list__items") |>
  html_nodes("div.beer-item__top") |>
  html_nodes("div.product-price") |>
  html_text() #|>
  #trimws() |>
  #stri_extract(regex = "\\d{1,}")
```

